### PR TITLE
Update lca.py

### PR DESCRIPTION
**Pull request by transfluxus**
fixed error print, when get_technosphere_exchange has more than 1 exchange

### CODE REVIEW

**Comment by transfluxus** [comment]
sorry, just saw, what the printer method is doing. please ignore

**Comment by transfluxus** [comment]
sorry, 
I did this blindly, because a colleague ran into that error.
I guess a solution as close as possible to original implementation would be

this import

from bw2data.backends import Exchange

and then

        def printer(x):
            return "{}|{}|{}".format(x['database'], x['name'], x['code'])

...
printer(Exchange(exchanges[0].input)),
printer(Exchange(exchanges[0].output)),

**Comment by cmutel** [comment]
HI @transfluxus! We can make changes if still needed here, but I don't see a linked issue or any understandable description of a missing feature or bug. Would you like to close this issue, or is there something here which we should still check out?

**Comment by transfluxus** [comment]
hehe, yes sorry for the messiest pull request ever. :)
It's a bug and causes an AttributeError.

exchanges[0] (type ExchangeDataset) has no attribute `input`, but the type Exchange has.

Then in printer
database, name, code are also no attributes of Exchange but are part of _data and accessed via ['<data-attr>']

**Comment by transfluxus** [comment]
I added a 2nd commit to the pull request that includes the fix

**Comment by transfluxus** [comment]
Hey,
since we are talking about multiple flows from the same in to same outs causing a problem for temporalis,
my colleague told me, that those are actually quite common in ecoinvent.

Is there a common way to resolve this?
Do we need to merge all flows with same in-outs beforehand? But then how would we be able to assign different times to different flows?

thanks!

**Comment by cmutel** [comment]
@transfluxus Can you post your question in a new issue or discussion and tag me? Thanks.

**Comment by cmutel** [comment]
Included in 0.9.3 release

**Pull request merged**
